name: admixture
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - pip
  - poetry
  - numpy
  - pandas
  - packaging
  - pytest
  - pytest-cov
  - ruff
  - mypy
  - quarto
  - pip:
      - -e .[dev]
