name: Documentation

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "README.md"
      - ".makim.yaml"
      - ".github/workflows/docs.yaml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
      - "README.md"
      - ".makim.yaml"
      - ".github/workflows/docs.yaml"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VIRTUALENV_ACTIVATORS: "bash,python"

jobs:
  render:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda.yaml
          activate-environment: admixture
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.12"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Render Quarto documentation
        run: makim --verbose docs.build

      - name: Upload rendered site
        uses: actions/upload-artifact@v4
        with:
          name: admixture-docs-site
          path: build
