name: Documentation

on:
  workflow_dispatch:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  VIRTUALENV_ACTIVATORS: "bash,python"

jobs:
  render:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: write
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda/dev-linux.yaml
          activate-environment: admixture
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.12"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Render Quarto documentation
        run: makim --verbose docs.build

      - name: Upload rendered site
        uses: actions/upload-artifact@v4
        with:
          name: admixture-docs-site
          path: build

      - name: Publish documentation to gh-pages
        if: github.event_name != 'pull_request'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: build
          force_orphan: true
