name: main

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  VIRTUALENV_ACTIVATORS: "bash,python"

jobs:
  unit:
    name: Python ${{ matrix.python-version }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - os: ubuntu-latest
            conda-env-file: conda/dev-linux.yaml
          - os: macos-latest
            conda-env-file: conda/dev-macos.yaml
          - os: windows-latest
            conda-env-file: conda/dev-win.yaml
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: ${{ matrix.conda-env-file }}
          activate-environment: admixture
          auto-update-conda: true
          conda-solver: libmamba
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Instantiate OpenADMIXTURE.jl
        run: makim --verbose setup.julia

      - name: Run unit tests
        run: makim --verbose tests.unit

  lint:
    name: Lint and type check
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda/dev-linux.yaml
          activate-environment: admixture
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.12"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Run lint and type checks
        run: makim --verbose lint.all
