name: Release

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4

      - uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-version: latest
          environment-file: conda.yaml
          activate-environment: admixture
          auto-update-conda: true
          conda-solver: libmamba
          python-version: "3.12"

      - name: Install dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install --with dev

      - name: Build package
        run: makim --verbose package.build
